# Official docker image.
image: docker:latest

# Docker in Docker
services:
  - docker:dind

# GitLab Project Settings -> CI/CD -> Variables
before_script:
  - apk add --no-cache bash
  - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"

build-master:
  stage: build
  script:
    - bash docker_build.sh
  only:
    - master
