os: linux
language: bash
services:
  - docker

env: 
  global:
    - REPO="elmarit/harbour"
    - TAG_LATEST="hb_34_latest"
    - MAKEFLAGS="-j 8"

stages:
  - base
  - compiler
  - hb3.2
  - hb3.4

before_install:
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin

jobs:
  include:
    - stage: base
      name: "Base OS images"
      script: 
        - ./docker_build.sh
        if: branch = master
          - docker push elmarit/harbour

    - stage: compiler
      name: "C/C++ compiler images"
      script: 
        - ./docker_compiler.sh
        if: branch = master
          - docker push elmarit/harbour

    - stage: hb3.2
      name: "Harbour Project 3.2"
      script:
        - docker build -t $REPO:hb_32_latest hb_32_latest/
        - docker tag $REPO:hb_32_latest $REPO:3.2
        if: branch = master
          - docker push elmarit/harbour
  
    - stage: hb3.4
      name: "Harbour Project 3.4.0 - Viktors"
      script: 
        - docker build -t $REPO:hb_34_latest hb_34_latest/
        - docker tag $REPO:hb_34_latest $REPO:latest
        - docker tag $REPO:hb_34_latest $REPO:3
        - docker tag $REPO:hb_34_latest $REPO:3.4
        - docker tag $REPO:hb_34_latest $REPO:3.4.0
        - docker tag $REPO:hb_34_latest $REPO:3.4.0dev
          if: branch = master
          - docker push elmarit/harbour
